package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Some tests for hh.ru")
    void generatedTest() {
        step("open https://hh.ru", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверка наличия текста \"QA\" в названии вакансии", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверка соответствия города вакансии: Екатеринбург", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверка соответствия вакансии на необходимый тип работы: удаленная работа", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверка соответствия вакансии на наличие необходимых навыков: Selenoid", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверка соответствия в ключевых навыках: Java", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://hh.ru'", () ->
            open("https://hh.ru"));

        step("Page title should have text 'Работа в Москве, поиск персонала и публикация вакансий - hh.ru'", () -> {
            String expectedTitle = "Работа в Москве, поиск персонала и публикация вакансий - hh.ru";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://hh.ru'", () ->
            open("https://hh.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}